### ISSUE TITLE
Classes in `vocabulary.xrm` cannot be numbers?

### ISSUE THREAD

**Issue by oschihin** [zazuko/xrm#155]
Hi
I am adding a new vocabulary to the `vocabulary.xrm`, it is `rdact: http://rdaregistry.info/termList/RDACarrierType`, used to declare the carrier of documentary material. Its classes are skos-Concepts in the form of numbers, so `rdact:1018` is "online ressource".
Adding this results in an error (`mismatched input '1018' expecting RULE_BLOCK_END(org.eclipse.xtext.diagnostics.Diagnostic.Syntax)`

![Image](https://github.com/user-attachments/assets/cb066fa2-c5bb-4bf9-886e-6a6f20114ab3)

Any ideas?

**Comment by mchlrch** [comment]
Hi @oschihin 

In this case, you need to [alias](https://github.com/zazuko/expressive-rdf-mapper/blob/main/documentation/mapping-language.md#aliasing-elements-that-have-special-characters-in-their-name) the number, for example like this:
```
classes
  _1018 "1018"
```

Then in the mapping use the alias identifier `_1018`:
```
types
  rdact._1018
```

**Comment by oschihin** [comment]
@mchlrch ah thanks, forgot about aliasing. But anyway, please note in the documentation that numbers need to be aliased. Closing here.
